[project]
name = "webscraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ischi Engels", email = "ischi.engels2830@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "click>=8.5.0",
    "pyspellchecker>=0.9.0",
    "requests>=2.34.2",
    "typer>=0.27.2",
]

[project.scripts]
webscraper = "webscraper:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
]
